name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Debug APK

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          channel: 'stable'

      # 3️⃣ Get dependencies
      - name: Get Flutter dependencies
        working-directory: everbloom
        run: flutter pub get

      # 4️⃣ Build debug APK (unsigned, but always works)
      - name: Build debug APK
        working-directory: everbloom
        run: flutter build apk --debug

      # 5️⃣ Upload generated APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: everbloom/build/app/outputs/flutter-apk/app-debug.apk
