name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Flutter APK

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      # 3️⃣ Get dependencies
      - name: Get Flutter dependencies
        working-directory: everbloom
        run: flutter pub get

      # 4️⃣ Build APK
      - name: Build release APK
        working-directory: everbloom
        run: flutter build apk --release

      # 5️⃣ Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: everbloom/build/app/outputs/flutter-apk/app-release.apk
